# Getting all archive creators in collection Flanders Architecture Institute, with authority data

SELECT ?archcreator ?archcreatorLabel ?archcreatorAltLabel ?archcreatorDescription ?geboortedatum ?overlijdensdatum ?geboorteplaatsLabel ?overlijdensplaatsLabel ?odisid 
WHERE { 
  ?archcreator wdt:P485 wd:Q14515828 . 
  OPTIONAL {?archcreator wdt:P569 ?geboortedatum .} 
  OPTIONAL {?archcreator wdt:P570 ?overlijdensdatum .} 
  OPTIONAL {?archcreator wdt:P19 ?geboorteplaats .} 
  OPTIONAL {?archcreator wdt:P20 ?overlijdensplaats .} 
  OPTIONAL {?archcreator wdt:P2372 ?odisid .} 
  SERVICE wikibase:label { bd:serviceParam wikibase:language "[AUTO_LANGUAGE],nl,en". } # If there is Dutch text, give me the Dutch text. If there is no Dutch text, give me the English text
}
